# development（开发环境）
server:
  port: 38088

# spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cat?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&serverTimezone=GMT%2B8
    username: cat
    password: cat_qwer@123
    druid:
      statViewServlet:
        loginUsername: admin
        loginPassword: admin
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
# log
logging:
  level:
    cn:
      int1024:
        cat: DEBUG
    com:
      zzg:
        mapper: DEBUG
