spring:
  profiles:
    active: dev
  application:
    name: cat
  output:
    ansi:
      enabled: ALWAYS
  redis:
    database: 1
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        minIdle: 0
        # 连接池中的最大空闲连接
        maxIdle: 8
        # 连接池的最大数据库连接数
        maxActive: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: -1ms
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # DruidFilterConfiguration
      filters: stat,wall,slf4j
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
          # 开启慢查询
          logSlowSql: true
          # 多少秒算慢查询
          slowSqlMillis: 2000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      webStatFilter:
        enabled: true
        #监控哪些
        urlPattern: "/*"
        #排除那些
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      statViewServlet:
        enabled: true
        urlPattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny:
        #  禁用HTML页面上的“Reset All”功能
        resetEnable: false
# my batis
mybatis:
  type-aliases-package: cn.int1024.cat.entity.po
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
# page helper
pagehelper:
  reasonable: false
  defaultCount: true
# 日志
logging:
  level:
    ch:
      qos:
        logback: WARN